
services:
  github-user: 
    image: "l3043y/github-user:latest"
    ports: 
      - "3000"
  nginx:
    image: nginx:latest
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - github-user
    ports:
      - "8080:8080"