import axios from "axios"
import { IUser } from "../components/User"

// Generated by https://quicktype.io
export interface IGitHubUser {
    login:               string;
    id:                  number;
    node_id:             string;
    avatar_url:          string;
    gravatar_id:         string;
    url:                 string;
    html_url:            string;
    followers_url:       string;
    following_url:       string;
    gists_url:           string;
    starred_url:         string;
    subscriptions_url:   string;
    organizations_url:   string;
    repos_url:           string;
    events_url:          string;
    received_events_url: string;
    type:                string;
    site_admin:          boolean;
}
// Generated by https://quicktype.io
export interface IGithubUserProfile {
    login:               string;
    id:                  number;
    node_id:             string;
    avatar_url:          string;
    gravatar_id:         string;
    url:                 string;
    html_url:            string;
    followers_url:       string;
    following_url:       string;
    gists_url:           string;
    starred_url:         string;
    subscriptions_url:   string;
    organizations_url:   string;
    repos_url:           string;
    events_url:          string;
    received_events_url: string;
    type:                string;
    site_admin:          boolean;
    name:                string;
    company:             string;
    blog:                string;
    location:            string;
    email:               null;
    hireable:            null;
    bio:                 null;
    twitter_username:    string;
    public_repos:        number;
    public_gists:        number;
    followers:           number;
    following:           number;
    created_at:          string;
    updated_at:          string;
}

export default async function fetchGithubUser(numberUser: number = 20){
    
    // Number of user validation
    if (! (0 < numberUser && numberUser <= 100) ){
        throw new Error(`${numberUser} is not between 1 and 100`);
    }

    // fetch 20 usernames from github user API 
    const githubAPIURL = `https://api.github.com/users?per_page=${numberUser}`
    const githubUserList = 
        await axios.get<IGitHubUser[]>(githubAPIURL)
        .then((res) => res.data)
        .catch((err) => {
            console.log(err)
            return [] as IGitHubUser[]
        })
    const loginList = githubUserList.map((user) => user.login)

    // fetch user profile containing number of follower and following
    const githubProfilePromise = loginList.map((login) => {
        const profilePromise = 
            axios.get<IGithubUserProfile>(`https://api.github.com/users/${login}`)
            .then((res) => res.data)
        return profilePromise
    })
    const githubProfileList: IGithubUserProfile[] = 
        await Promise.all(githubProfilePromise)
        .catch((err) => {
            console.log(err)
            return [] as IGithubUserProfile[]
        })

    // extract relevent information
    const users:IUser[] = githubProfileList.map((profile:IGithubUserProfile) =>{
        const user: IUser = {
            id: profile.id,
            userAvatarUrl: profile.avatar_url,
            userName: profile.login,
            numberFollowing: profile.following,
            NumberFollower: profile.followers
        }
        return user
    })

    return users
}