import axios from "axios"
import { IUser } from "../components/User"

// Generated by https://quicktype.io
export interface IGitHubUser {
    login:               string;
    id:                  number;
    node_id:             string;
    avatar_url:          string;
    gravatar_id:         string;
    url:                 string;
    html_url:            string;
    followers_url:       string;
    following_url:       string;
    gists_url:           string;
    starred_url:         string;
    subscriptions_url:   string;
    organizations_url:   string;
    repos_url:           string;
    events_url:          string;
    received_events_url: string;
    type:                string;
    site_admin:          boolean;
}
// Generated by https://quicktype.io
export interface IGithubUserProfile {
    login:               string;
    id:                  number;
    node_id:             string;
    avatar_url:          string;
    gravatar_id:         string;
    url:                 string;
    html_url:            string;
    followers_url:       string;
    following_url:       string;
    gists_url:           string;
    starred_url:         string;
    subscriptions_url:   string;
    organizations_url:   string;
    repos_url:           string;
    events_url:          string;
    received_events_url: string;
    type:                string;
    site_admin:          boolean;
    name:                string;
    company:             string;
    blog:                string;
    location:            string;
    email:               null;
    hireable:            null;
    bio:                 null;
    twitter_username:    string;
    public_repos:        number;
    public_gists:        number;
    followers:           number;
    following:           number;
    created_at:          string;
    updated_at:          string;
}
export default async function fetchUsers(){
    
    // fetch 20 usernames from github user API 
    const githubAPIURL = 'https://api.github.com/users?per_page=20'
    const githubUserList = await axios.get<IGitHubUser[]>(githubAPIURL)
    const loginList = githubUserList.data.map((user) => {
        return user.login
    })

    // fetch user profile containing number of follower and following
    const githubProfilePromise = loginList.map((login) => {
        return axios.get<IGithubUserProfile>(`https://api.github.com/users/${login}`)
            .then((res) => res.data)
    })
    const githubProfileList = await Promise.all(githubProfilePromise)

    // extract relevent information
    const users = githubProfileList.map((profile:IGithubUserProfile) =>{
        const user: IUser = {
            id: profile.id,
            userAvatarUrl: profile.avatar_url,
            userName: profile.login,
            numberFollowing: profile.following,
            NumberFollower: profile.followers
        }
        return user
    })

    return users
}